modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "exposure_expanded"
version = "${version}"
displayName = "Exposure: Expanded"
authors = "Sparkwave"
description = '''
Addon for Exposure that adds new lenses.
'''
#logoFile = ""

[[dependencies.exposure_expanded]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.exposure_expanded]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.exposure_expanded]]
modId = "exposure"
type = "required"
mandatory = true
versionRange = "[1.9.2,)"
ordering = "AFTER"
side = "BOTH"
reason = "This is an addon for Exposure. It requires the base mod."

[[dependencies.exposure_expanded]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.exposure_expanded]]
modId = "create"
type = "required"
versionRange = "[6.0.1,)"
ordering = "AFTER"
side = "BOTH"


[[mixins]]
config = "exposure_expanded.mixins.json"
